** TBA
   :PROPERTIES:
   :CUSTOM_ID: tba
   :END:

By [[][Denis Dutoit]]([[https://www.leti-cea.com][CEA LETI]])

TBA

*TBA

** What does the space industry expect from RISC-V?
   :PROPERTIES:
   :CUSTOM_ID: what-does-the-space-industry-expect-from-risc-v
   :END:

By [[][Antoine Certain]]([[][Airbus Defence & Space]])

The space industry has some particularities which makes the usage of
COTS components quite difficult. But, with the emergence of new space
designs based on COTS, the space industry open its doors to a bigger
ecosystem. And the RISC V ecosystem could answer to the major
requirements of spacecraft design. This presentation will present the
main requirements such industry expect from a core IP.

*Antoine CERTAIN is an experienced hardware and software architect on
embedded data-handling applications on spacecraft. He has gained large
scale of space knowledge thanks to several projects for ESA, CNES and
internally to Airbus Defence and Space. He is now team leader of the R&D
On board data processing team of Airbus Defence and Space in Toulouse,
FR.

** Development of a RV64GC IP core for the GRLIB IP Library
   :PROPERTIES:
   :CUSTOM_ID: development-of-a-rv64gc-ip-core-for-the-grlib-ip-library
   :END:

By [[][Jan Andersson]]([[https://www.gaisler.com][Cobham Gaisler]])

Cobham Gaisler is a world leader for space computing solutions where the
company provides radiation tolerant system-on-chip devices based around
the LEON processors. The building blocks for these devices are also
available as IP cores from the company in an IP library named GRLIB.
Cobham Gaisler is currently developing a RV64GC core that will be
provided as part of GRLIB. The presentation will cover features of the
IP core and how it fits with existing peripherals, with technical items
we see missing in the specification.

*Mr Jan Andersson is working at Cobham Gaisler as Director of
Engineering, overseeing hardware and software development efforts. Its
key competencies are in management of projects developing complex
digital systems, microprocessor architecture, fault-tolerance concepts,
use of programmable logic, Field Programmable Gate Arrays for
applications both in consumer electronics and harsh environments. He
holds a Master of Science degree in Computer Engineering focused on
digital design and embedded systems.

** TBA
   :PROPERTIES:
   :CUSTOM_ID: tba-1
   :END:

By [[][TBA]]([[][]])

TBA

*TBA

** Achieving determinism and performance on the RISC-V FlexPRET
Processor
   :PROPERTIES:
   :CUSTOM_ID: achieving-determinism-and-performance-on-the-risc-v-flexpret-processor
   :END:

By [[][Eric Jenn]]([[http://www.irt-saintexupery.com/][IRT
Saint-Exupéry]])

Performance improvement usually comes at the cost of temporal
determinism. Trading better average performance for a loss of
predictability is sometimes acceptable, but it is not for
safety-critical applications where the time at which a value is produced
is often as important as the value itself. In this talk, we address the
question of temporal determinism, which is a prerequisite to
dependability. We show how we combine a deterministic programming model
with a deterministic hardware architecture and an “holistic”
optimization process to achieve both performance and dependability. This
work is applied on the MultiPRET processor, a "multicore" declination of
the RiscV FlexPRET PREcision Timed Architecture (PRET) proposed by the
University of California at Berkeley.

*Dr Eric Jenn is a research engineer at Thales AVS. He is currently
managing the Critical Applications on Predictable High-Performance
Computing Architectures (CAPHCA) collaborative research project at IRT
Saint-Exupéry in Toulouse. Dr Jenn has been working in the area of
safety critical systems for around 30 years, both on the analysis and
development of nuclear and avionics systems. His interests cover all
aspects of the development of dependable real-time systems, including
certification, system modeling and design, real-time software
development, formal verification, and microarchitecture design. He has
participated in many collaborative research projects involving academic
and industrial partners, including GUARDS, Diana, SPICES, ESPASS, P,
etc.

** TBA
   :PROPERTIES:
   :CUSTOM_ID: tba-2
   :END:

By [[http://www.informatik.uni-bremen.de/~grosse/][Daniel
Große]]([[https://www.uni-bremen.de][University of Bremen]])

TBA

*TBA

** TBA
   :PROPERTIES:
   :CUSTOM_ID: tba-3
   :END:

By
[[][TBA]]([[https://www.thalesgroup.com/en/global/innovation/research-and-technology][Thales
Research & Technology]])

TBA

*TBA
