#+STARTUP: showall
#+OPTIONS: toc:nil
#+title: RISC-V Week: Overview

* Your RISC-V Week

The /RISC-V Week/ merges two events, from October 1st to 3rd
2019 in Paris:

- The [[#rencontres][/2nd RISC-V Meeting/]], organised by [[http://www.irtnanoelec.fr][IRT Nanoelec]] and the [[http://www.cea.fr][CEA]], will
  take place at [[https://espace-van-gogh.com][Espace Van Gogh]], [[https://www.openstreetmap.org/?mlat=48.84337&mlon=2.37081#map=19/48.84337/2.37081][62 quai de la Rapée]]:
  - Tuesday October 1st, from 10:00 to 18:00 -- registration from 9:00.
  - Wednesday October 2nd, from 9:00 to 18:00.
  This event is sponsored by:
#+INCLUDE: "pages/sponsors-table.org"

- The /[[#scientific-day][Scientific Day of IRT SE & GDR SOC2: RISC-V for critical
  embedded systems]]/ organised by [[http://www.irt-saintexupery.com][IRT St-Exupéry]] and [[http://www.gdr-soc.cnrs.fr][GDR SOC2]], will
  take place on the [[https://fr.wikipedia.org/wiki/Campus_de_Jussieu][Jussieu campus]]:
  - Thursday October 3rd, from 9:00 to 17:15.

** /2nd RISC-V Meeting/
:PROPERTIES:
:CUSTOM_ID: rencontres
:END:

The RISC-V architecture, which comes from academia, is challenging
several communities.

 - It opens the architecture and hardware design communities to the
   dynamics of open source;
 - Language, compilation, operating system, security or safety
   communities can now influence the definition of hardware
   architectures;
 - More generally, it allows hardware, software and system communities
   to experiment together.

After the first /1st RISC-V Meeting/ on /academic
opportunities/ held in Grenoble in October 2018, the second edition
will take place in Paris on October 1st and 2nd 2019. They are open to the
academic and industrial worlds and they will address several important
topics:

 1. The impact of the arrival of open-source on the design of systems
    on a chip (SoC), embedded systems or cyber-physics (CPS).
 2. Legal and strategic intellectual property (IP) issues, ranging
    from public management of hardware open source code, to
    sovereignty issues.
 3. Identifying collaboration points between the
    hardware, software, and systems communities.
 4. Facilitating collaboration between academic research and industry.

To allow as much time as possible for exchanges the core of
the program is made up of multiple sessions, with a small number of short
contributions followed by a time for group discussion. The
program also includes a number of tutorials on key RISC-V issues and
solutions, and high-level keynotes.

*** Program Committee

The Program Committee is comprises:

- Thierry Collette, [[https://www.thalesgroup.com/fr/global/innovation/recherche-technologie][Thales R&T]]
- [[https://fr.linkedin.com/in/christianfabre][Christian Fabre]], [[http://www.cea.fr][CEA]], chair
- Eric Flamand, [[https://greenwaves-technologies.com][GreenWaves Technologies]]
- Pierre Gobin, [[https://www.st.com][STMicroelectronics]]
- Nicolas Hili, [[http://www.irt-saintexupery.com][IRT Saint-Exupéry]]
- David Hély, [[http://www.grenoble-inp.fr][INPG]]/[[http://lcis.grenoble-inp.fr][LCIS]]
- Mathieu Jan, [[http://www.cea.fr][CEA]]
- [[http://www-labsticc.univ-ubs.fr/~kmartin][Kevin Martin]], [[http://www.univ-ubs.fr][UBS]]/[[http://labsticc.fr][Lab-STICC]]
- Ivan Miró-Panadès, [[http://www.cea.fr][CEA]]
- Ahmed Ould El Hacen, [[https://www.wisekey.com][Wisekey]]
- Thomas Peyret, [[http://www.cea.fr][CEA]]
- Frederic Pétrot, [[http://www.grenoble-inp.fr][INPG]]/[[http://tima.univ-grenoble-alpes.fr/tima][TIMA]]
- Olivier Savry, [[http://www.cea.fr][CEA]], co-chair
- Olivier Sentieys, [[https://www.inria.fr][INRIA]]

*** Organisation Committee

The Organisation Committee comprises:
- Jean-Philippe Blanc, [[http://www.irtnanoelec.fr][IRT Nanoelec]]
- Damien Couroussé, [[http://www.cea.fr][CEA]]
- Laurent-Frédéric Ducreux, [[http://www.irtnanoelec.fr][IRT Nanoelec]], co-chair
- [[https://fr.linkedin.com/in/christianfabre][Christian Fabre]], [[http://www.cea.fr][CEA]], chair
- Mathieu Jan, [[http://www.cea.fr][CEA]]
- Didier Louis, [[http://www.cea.fr][CEA]]
- Thomas Peyret, [[http://www.cea.fr][CEA]]
- Olivier Savry, [[http://www.cea.fr][CEA]], co-chair

*** Contact

The Organising Committee can be reached at:
[[mailto:organisation@open-src-soc.org][~organisation@open-src-soc.org~]].


** /Scientific Day IRT St-Exupéry & GDR SOC2:/ /RISC-V for critical embedded systems/
:PROPERTIES:
:CUSTOM_ID: scientific-day
:END:

[[http://www.irt-saintexupery.com][IRT Saint-Exupéry]] & [[http://www.gdr-soc.cnrs.fr][GDR SOC2]] continue their cooperation with the
organisation of their 3rd scientific day gathering industry and
academia on /critical embedded systems/.

This year, the scientific day will be held in Paris, in partnership
with the /2nd RISC-V Meeting/ and as part of the /RISC-V Week/. It
will focus on the opportunities offered by RISC-V and open hardware
solutions for critical embedded systems.

The day will include extensive presentations by guest speakers from
academia and industry on the following topics:

- Industrial needs and requirements
- Hardware design
- Design tools for critical systems

*** Organisation Commitee

The Organisation Committee comprises: Philippe Cuenot ([[http://www.irt-saintexupery.com][IRT
St-Exupéry]], Continental), Sébastien Faucou ([[https://www.ls2n.fr/][LS2N]], [[https://www.univ-nantes.fr][Université de Nantes]]), Maxime Pelcat ([[https://www.ietr.fr/][IETR]], [[https://www.insa-rennes.fr/][INSA de Rennes]]).

*** Contact

The Organisation Committee from the /Scientific Day of [[http://www.irt-saintexupery.com][IRT
Saint-Exupéry]] & [[http://www.gdr-soc.cnrs.fr][GDR SOC2]]/ can be reached at
[[mailto:contact-3oct@open-src-soc.org][=contact-3oct@open-src-soc.org=]].
